name: CI/CD for Microservices

on:
  push:
    branches:
      - main  # Lắng nghe sự kiện trên nhánh 'main' của repo tổng
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy (auth_service, file_service, spring_cloud_gateway, or all)'
        required: true
        default: 'all'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

  build-and-test:
    runs-on: ubuntu-latest
    needs: update-submodules
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: ''

      - name: Build and Test All Services
        run: |
          if [ "${{ github.event.inputs.service }}" == "all" ]; then
            ./mvnw clean install
            docker-compose -f docker-compose.yml up --build -d
          elif [ "${{ github.event.inputs.service }}" == "auth_service" ]; then
            cd auth_service
            ./mvnw clean install
            docker-compose -f docker-compose.yml up --build -d auth-service
          elif [ "${{ github.event.inputs.service }}" == "file_service" ]; then
            cd file_service
            ./mvnw clean install
            docker-compose -f docker-compose.yml up --build -d file-service
          else
            echo "Invalid service specified."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy Microservices
        run: |
          if [ "${{ github.event.inputs.service }}" == "all" ]; then
            docker-compose -f docker-compose.yml up -d
          elif [ "${{ github.event.inputs.service }}" == "auth_service" ]; then
            docker-compose -f docker-compose.yml up -d auth-service
          elif [ "${{ github.event.inputs.service }}" == "file_service" ]; then
            docker-compose -f docker-compose.yml up -d file-service
          else
            echo "Invalid service specified."
            exit 1
          fi
